/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_System.h"

void *
append_1_svc(ordered *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Append recieved");

	return (void *) &result;
}

int *
query_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("query recieved for index %d", *argp);

	return &result;
}

void *
remove_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("remove recieved for index %d", *argp);

	return (void *) &result;
}
