/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_System.h"

ordered list;

void *append_1_svc(ordered *argp, struct svc_req *rqstp)
{
	static char * result;
	int i=0, j=0;
	list.ordered_len += argp->ordered_len;
	int first = 1;

	// First time numbers are appended, list is empty
	if (list.ordered_len == 8 && first) {
		list.ordered_val = malloc(((argp->ordered_len * sizeof(int))));
		list = *argp;
		first = 0;
	}
	else {
		//
		list.ordered_val = realloc(list.ordered_val, ((list.ordered_len * sizeof(int)) + 1));
	
		int end = list.ordered_len - argp->ordered_len;
		
		for (int i = 0; i < argp->ordered_len; i++) {
			list.ordered_val[i+end] = argp->ordered_val[i];
		}
	}

	return (void *) &result;
}

int * query_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	int i = *argp;

	result = -1;
	if (i < list.ordered_len) {
		result = list.ordered_val[i];
	}

	return &result;
}

void * remove_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	int rem = *argp;

	list.ordered_len -= 1;

	for (int i = rem; i < list.ordered_len; i++) {
		list.ordered_val[i] = list.ordered_val[i+1];
	}

	return (void *) &result;
}
