/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_SYSTEM_H_RPCGEN
#define _RPC_SYSTEM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int ordered_len;
	int *ordered_val;
} ordered;

#define RPC_SYSTEM_PROGRAM 0x20000001
#define RPC_SYSTEM_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define APPEND 1
extern  void * append_1(ordered *, CLIENT *);
extern  void * append_1_svc(ordered *, struct svc_req *);
#define QUERY 2
extern  int * query_1(int *, CLIENT *);
extern  int * query_1_svc(int *, struct svc_req *);
#define REMOVE 3
extern  void * remove_1(int *, CLIENT *);
extern  void * remove_1_svc(int *, struct svc_req *);
extern int rpc_system_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define APPEND 1
extern  void * append_1();
extern  void * append_1_svc();
#define QUERY 2
extern  int * query_1();
extern  int * query_1_svc();
#define REMOVE 3
extern  void * remove_1();
extern  void * remove_1_svc();
extern int rpc_system_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ordered (XDR *, ordered*);

#else /* K&R C */
extern bool_t xdr_ordered ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_SYSTEM_H_RPCGEN */
