/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC_System.h"


void
rpc_system_program_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	ordered  append_1_arg;
	int  *result_2;
	int  query_1_arg;
	void  *result_3;
	int  remove_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_SYSTEM_PROGRAM, RPC_SYSTEM_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit(1);
	}
#endif	/* DEBUG */

	char req;
	printf("Enter request type: ");
	scanf("%c", &req);

	if (req == 'a' || req == 'A'){
		printf("Enter 8 elements\n");
		int input[8];
		
		for (int i = 0; i < 8; i++) {
			scanf("%d", &input[i]);
		}

		for (int i = 0; i < 8; i++) {
			printf("%d,", input[i]);
		}
		printf("\n");

		// Add elements to new ordered list
		ordered list;
		//list.ordered_len = 8;
		list.ordered_val = input;

		append_1(&list, clnt);
	}
	else if (req == 'q' || req == 'Q') {
		printf("Enter the index to query: \n");
		int index;
		scanf("%d", &index);
		query_1(&index, clnt);
	}
	else if (req == 'r' || req == 'r'){
		printf("Enter the index to remove: \n");
		int index;
		scanf("%d", &index);
		remove_1(&index, clnt);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host = "localhost";

	if (argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	rpc_system_program_1 (host);
	
	exit (0);
}
