/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_System.h"

bool_t
xdr_ordered(XDR *xdrs, ordered *objp)
{

	if (!xdr_array(xdrs, (char **)&objp->ordered_val, (u_int *)&objp->ordered_len, ~0, sizeof(int), (xdrproc_t)xdr_int))
		return (FALSE);
	return (TRUE);
}
